// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SANoAuthFinalProj.Models;
using System;

namespace SANoAuthFinalProj.Migrations
{
    [DbContext(typeof(SAAppContext))]
    [Migration("20180305233425_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SANoAuthFinalProj.Models.DataPoint", b =>
                {
                    b.Property<DateTime>("TimeStamp");

                    b.Property<double>("BMI");

                    b.Property<int>("CaloriesBurned");

                    b.Property<int>("CaloriesIn");

                    b.Property<int>("CarbsConsumed");

                    b.Property<int>("FatConsumed");

                    b.Property<int>("FiberConsumed");

                    b.Property<int>("ID");

                    b.Property<int>("MinutesAsleep");

                    b.Property<int>("MinutesAwake");

                    b.Property<int>("ProteinConsumed");

                    b.Property<int>("SodiumConsumed");

                    b.Property<int>("Steps");

                    b.Property<int>("WaterConsumed");

                    b.Property<double>("Weight");

                    b.HasKey("TimeStamp");

                    b.HasIndex("ID");

                    b.ToTable("DataPoint");
                });

            modelBuilder.Entity("SANoAuthFinalProj.Models.Sensor", b =>
                {
                    b.Property<int>("ID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Sensor");
                });

            modelBuilder.Entity("SANoAuthFinalProj.Models.DataPoint", b =>
                {
                    b.HasOne("SANoAuthFinalProj.Models.Sensor")
                        .WithMany("DataPoints")
                        .HasForeignKey("ID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
